### ISSUE TITLE
Downloading header for ensemblToGeneName (hg18): ERROR: Failed to get header.

### ISSUE THREAD

**Issue by nickytong** [yarden/rnaseqlib#11]
Hello Yarden,

I'm trying to use rnaseqlib to call miso. I'm at the first stage to get rnaseqlib working.
The following is the command I ran:

rna_pipeline --init hg18 --output-dir pipeline_init

The output:

---

Checking that all required programs are available...
Found all required programs.
Initializing RNA base...
Fetching sequences..
Downloading genome sequence files for hg18
- Output dir: /home/ubuntu/opt/rnaseqlib/pipeline_init/hg18
  Directory /home/ubuntu/opt/rnaseqlib/pipeline_init/hg18/genome exists and contains files; skipping download of genome...
  chrRibo exists. Skipping download..
  Fetching tables..
  Download UCSC tables...
- Output dir: /home/ubuntu/opt/rnaseqlib/pipeline_init/hg18/ucsc
  Downloading all UCSC headers for hg18
- Output dir: /home/ubuntu/opt/rnaseqlib/pipeline_init/hg18/ucsc/headers
  Downloading header for knownGene (hg18)
  Downloading header for kgXref (hg18)
  Downloading header for knownToEnsembl (hg18)
  Downloading header for knownAlt (hg18)
  Downloading header for knownIsoforms (hg18)
  Downloading header for ensGene (hg18)
  Downloading header for ensemblToGeneName (hg18)
  ERROR: Failed to get header.
  Standard output was: 
  Standard error was: 
  ERROR 1146 (42S02) at line 1: Table 'hg18.ensemblToGeneName' doesn't exist

---

I further pinpointed the actual command (from download_ucsc_table_header) as below:

/usr/bin/mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -D hg18 -e 'desc ensemblToGeneName' -N -B

the output is:
ERROR 1146 (42S02) at line 1: Table 'hg18.ensemblToGeneName' doesn't exist

Thank you very much,

Pan

**Comment by yarden** [comment]
Hi Pan,

Thanks. I just checked in a new version that should hopefully fix this. Can you try it? It's in the `clip` branch (default branch) of GitHub. 

Best, --Yarden

**Comment by nickytong** [comment]
Thanks for your prompt response.
Now the program continues, although an error message is showing. Now sure if this is expected.

---

Downloading header for knownGene (hg18)
Downloading header for kgXref (hg18)
Downloading header for knownToEnsembl (hg18)
Downloading header for knownAlt (hg18)
Downloading header for knownIsoforms (hg18)
Downloading header for ensGene (hg18)
Downloading header for ensemblToGeneName (hg18)
ERROR: Failed to get header.
Standard output was: 
Standard error was: 
ERROR 1146 (42S02) at line 1: Table 'hg18.ensemblToGeneName' doesn't exist
Skipping ensemblToGeneName
Downloading header for ensGtp (hg18)
Downloading header for refGene (hg18)
Downloading header for tRNAs (hg18)
Downloading knownGene.txt.gz
.....

**Comment by yarden** [comment]
That's correct output, it's just saying that it failed to get ensemblToGeneName. This is simply because ensemblToGeneName does not exist for hg18, but exists for other genomes (like mm9 and hg19). Unfortunately UCSC is not consistent with the tables that are offered for each genome, so sometimes a later genome (like hg19) has tables that an older genome (like hg18) doesn't have. Internally, rnaseqlib makes do without this table for hg18 so it should still work.
